
# Basic
title: Alex Li Tech Blog
subtitle: Make Chumi iOS app better
welcome_message: <a href="https://itunes.apple.com/app/apple-store/id1118531323?mt=8" target="_blank">Download the chumi app</a>
description: New features have been adding, old features had been removing, developers are changing, finally we found the market fit, and started to worry about code quality.
creator: <a href="https://github.com/yitaolee/">@yitaolee</a>

url: "http://chumi.co"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: yitaolee
    mail: yitaolee1991@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
